# published as reboot8/redkvmysql
FROM mysql:5.7.22
ENV MYSQL_ROOT_PASSWORD=my-secret-root-pw \
    MYSQL_DATABASE=redkv_test \
    MYSQL_HOST=127.0.0.1 \
    MYSQL_ROOT_HOST=% \
    MYSQL_USER=redtester \
    MYSQL_PASSWORD=redtesterpwd

